import 'package:ae_live/theme/custom_colors_schemes.g.dart';
import 'package:ae_live/theme/custom_snack_bar_theme.dart';
import 'package:ae_live/theme/custom_text_theme.g.dart';
import 'package:flutter/material.dart';

// const lightColorScheme = ColorScheme(
//   brightness: Brightness.light,
//   primary: Color(0xFFBD1400),
//   onPrimary: Color(0xFFFFFFFF),
//   primaryContainer: Color(0xFFFFDAD4),
//   onPrimaryContainer: Color(0xFF400200),
//   secondary: Color(0xFF775650),
//   onSecondary: Color(0xFFFFFFFF),
//   secondaryContainer: Color(0xFFFFDAD4),
//   onSecondaryContainer: Color(0xFF2C1511),
//   tertiary: Color(0xFF6F5C2E),
//   onTertiary: Color(0xFFFFFFFF),
//   tertiaryContainer: Color(0xFFFAE0A6),
//   onTertiaryContainer: Color(0xFF251A00),
//   error: Color(0xFFBA1A1A),
//   errorContainer: Color(0xFFFFDAD6),
//   onError: Color(0xFFFFFFFF),
//   onErrorContainer: Color(0xFF410002),
//   background: Color(0xFFFFFBFF),
//   onBackground: Color(0xFF201A19),
//   surface: Color(0xFFFFFBFF),
//   onSurface: Color(0xFF201A19),
//   surfaceVariant: Color(0xFFF5DDD9),
//   onSurfaceVariant: Color(0xFF534340),
//   outline: Color(0xFF857370),
//   onInverseSurface: Color(0xFFFBEEEB),
//   inverseSurface: Color(0xFF362F2D),
//   inversePrimary: Color(0xFFFFB4A6),
//   shadow: Color(0xFF000000),
//   surfaceTint: Color(0xFFBD1400),
//   outlineVariant: Color(0xFFD8C2BE),
//   scrim: Color(0xFF000000),
// );

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF00629D),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFCFE5FF),
  onPrimaryContainer: Color(0xFF001D34),
  secondary: Color(0xFF526070),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFD5E4F7),
  onSecondaryContainer: Color(0xFF0E1D2A),
  tertiary: Color(0xFF695779),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFF0DBFF),
  onTertiaryContainer: Color(0xFF231532),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  background: Color(0xFFFCFCFF),
  onBackground: Color(0xFF1A1C1E),
  surface: Color(0xFFFCFCFF),
  onSurface: Color(0xFF1A1C1E),
  surfaceVariant: Color(0xFFDEE3EB),
  onSurfaceVariant: Color(0xFF42474E),
  outline: Color(0xFF72777F),
  onInverseSurface: Color(0xFFF1F0F4),
  inverseSurface: Color(0xFF2F3033),
  inversePrimary: Color(0xFF99CBFF),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF00629D),
  outlineVariant: Color(0xFFC2C7CF),
  scrim: Color(0xFF000000),
);

final lightTheme = ThemeData(
  useMaterial3: true,
  colorScheme: lightColorScheme,
  scaffoldBackgroundColor: lightColorScheme.background,
  textTheme: customTextTheme,
  snackBarTheme: customSnackBarTheme,
  extensions: [
    lightCustomColors,
  ],
  appBarTheme: const AppBarTheme(
    centerTitle: true,
  ),
);

// const darkColorScheme = ColorScheme(
//   brightness: Brightness.dark,
//   primary: Color(0xFFFFB4A6),
//   onPrimary: Color(0xFF660600),
//   primaryContainer: Color(0xFF900D00),
//   onPrimaryContainer: Color(0xFFFFDAD4),
//   secondary: Color(0xFFE7BDB5),
//   onSecondary: Color(0xFF442A25),
//   secondaryContainer: Color(0xFF5D3F3A),
//   onSecondaryContainer: Color(0xFFFFDAD4),
//   tertiary: Color(0xFFDDC48C),
//   onTertiary: Color(0xFF3D2E04),
//   tertiaryContainer: Color(0xFF564519),
//   onTertiaryContainer: Color(0xFFFAE0A6),
//   error: Color(0xFFFFB4AB),
//   errorContainer: Color(0xFF93000A),
//   onError: Color(0xFF690005),
//   onErrorContainer: Color(0xFFFFDAD6),
//   background: Color(0xFF201A19),
//   onBackground: Color(0xFFEDE0DD),
//   surface: Color(0xFF201A19),
//   onSurface: Color(0xFFEDE0DD),
//   surfaceVariant: Color(0xFF534340),
//   onSurfaceVariant: Color(0xFFD8C2BE),
//   outline: Color(0xFFA08C89),
//   onInverseSurface: Color(0xFF201A19),
//   inverseSurface: Color(0xFFEDE0DD),
//   inversePrimary: Color(0xFFBD1400),
//   shadow: Color(0xFF000000),
//   surfaceTint: Color(0xFFFFB4A6),
//   outlineVariant: Color(0xFF534340),
//   scrim: Color(0xFF000000),
// );

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFF99CBFF),
  onPrimary: Color(0xFF003355),
  primaryContainer: Color(0xFF004A78),
  onPrimaryContainer: Color(0xFFCFE5FF),
  secondary: Color(0xFFB9C8DA),
  onSecondary: Color(0xFF243240),
  secondaryContainer: Color(0xFF3A4857),
  onSecondaryContainer: Color(0xFFD5E4F7),
  tertiary: Color(0xFFD4BEE6),
  onTertiary: Color(0xFF392A49),
  tertiaryContainer: Color(0xFF504060),
  onTertiaryContainer: Color(0xFFF0DBFF),
  error: Color(0xFFFFB4AB),
  errorContainer: Color(0xFF93000A),
  onError: Color(0xFF690005),
  onErrorContainer: Color(0xFFFFDAD6),
  background: Color(0xFF000000),
  onBackground: Color(0xFFE2E2E5),
  surface: Color(0xFF000000),
  onSurface: Color(0xFFE2E2E5),
  surfaceVariant: Color(0xFF42474E),
  onSurfaceVariant: Color(0xFFC2C7CF),
  outline: Color(0xFF8C9199),
  onInverseSurface: Color(0xFF1A1C1E),
  inverseSurface: Color(0xFFE2E2E5),
  inversePrimary: Color(0xFF00629D),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF99CBFF),
  outlineVariant: Color(0xFF42474E),
  scrim: Color(0xFF000000),
);

final darkTheme = ThemeData(
  useMaterial3: true,
  colorScheme: darkColorScheme,
  scaffoldBackgroundColor: darkColorScheme.background,
  textTheme: customTextTheme,
  snackBarTheme: customSnackBarTheme,
  extensions: [
    darkCustomColors,
  ],
);
