import 'package:ae_live/models/hospital_info_model.dart';

final List<HospitalInfoModel> hospitalInfo = <HospitalInfoModel>[
  HospitalInfoModel(
    nameTC: '雅麗氏何妙齡那打素醫院',
    nameSC: '雅丽氏何妙龄那打素医院',
    nameEN: 'Alice Ho Miu Ling Nethersole Hospital',
    contactNo: '2689 2000',
    faxNo: '2662 1690',
    emailAddress: 'ahnh_enquiry@ha.org.hk',
    website: 'http://www3.ha.org.hk/ahnh/',
  ),
  HospitalInfoModel(
    nameTC: '明愛醫院',
    nameSC: '明爱医院',
    nameEN: 'Caritas Medical Centre',
    contactNo: '3408 5678',
    faxNo: '2785 5755',
    emailAddress: 'cmc.enq@ha.org.hk',
  ),
  HospitalInfoModel(
    nameTC: '廣華醫院',
    nameSC: '广华医院',
    nameEN: 'Kwong Wah Hospital',
    contactNo: '2332 2311',
    faxNo: '3517 5481',
    emailAddress: 'kwh.enquiry@ha.org.hk',
    website: 'http://www.ha.org.hk/kwh/default.htm',
  ),
  HospitalInfoModel(
    nameTC: '北區醫院',
    nameSC: '北区医院',
    nameEN: 'North District Hospital',
    contactNo: '2683 8888',
    faxNo: '2683 8383',
    emailAddress: 'ndh_enquiry@ha.org.hk',
    website: 'http://www3.ha.org.hk/ndh/index.htm',
  ),
  HospitalInfoModel(
    nameTC: '北大嶼山醫院',
    nameSC: '北大屿山医院',
    nameEN: 'North Lantau Hospital',
    contactNo: '3467 7000',
    faxNo: '3467 7004',
    emailAddress: 'nlth.enquiry@ha.org.hk',
  ),
  HospitalInfoModel(
    nameTC: '瑪嘉烈醫院',
    nameSC: '玛嘉烈医院',
    nameEN: 'Princess Margaret Hospital',
    contactNo: '2990 1111',
    faxNo: '2786 3629',
    emailAddress: 'pmh.enquiry@ha.org.hk',
  ),
  HospitalInfoModel(
    nameTC: '博愛醫院',
    nameSC: '博爱医院',
    nameEN: 'Pok Oi Hospital',
    contactNo: '2486 8000',
    faxNo: '2443 9593',
    emailAddress: 'poh.service@ha.org.hk',
    website: 'https://www.ha.org.hk/poh/',
  ),
  HospitalInfoModel(
    nameTC: '威爾斯親王醫院',
    nameSC: '威尔斯亲王医院',
    nameEN: 'Prince of Wales Hospital',
    contactNo: '3505 2211',
    faxNo: '2637 8244',
    emailAddress: 'pwh_enquiry@ha.org.hk',
    website: 'http://www3.ha.org.hk/pwh/index.htm',
  ),
  HospitalInfoModel(
    nameTC: '東區尤德夫人那打素醫院',
    nameSC: '东区尤德夫人那打素医院',
    nameEN: 'Pamela Youde Nethersole Eastern Hospital',
    contactNo: '2595 6111',
    faxNo: '2515 0794',
    emailAddress: 'pyneh_enquiry@ha.org.hk',
    website: 'http://www.ha.org.hk/pyneh',
  ),
  HospitalInfoModel(
    nameTC: '伊利沙伯醫院',
    nameSC: '伊利沙伯医院',
    nameEN: 'Queen Elizabeth Hospital',
    contactNo: '3506 8888',
    faxNo: '3506 8951',
    emailAddress: 'qeh_webmaster@ha.org.hk',
    website: 'http://www.ha.org.hk/qeh',
  ),
  HospitalInfoModel(
    nameTC: '瑪麗醫院',
    nameSC: '玛丽医院',
    nameEN: 'Queen Mary Hospital',
    contactNo: '2255 3838',
    faxNo: '2817 5496',
    emailAddress: 'qmh_enquiry@ha.org.hk',
    website: 'http://www.ha.org.hk/qmh',
  ),
  HospitalInfoModel(
    nameTC: '律敦治醫院',
    nameSC: '律敦治医院',
    nameEN: 'Ruttonjee Hospital',
    contactNo: '2291 2000',
    faxNo: '2591 6886',
    emailAddress: 'rtskh_enquiry@ha.org.hk',
    website: 'http://www.ha.org.hk/rtskh',
  ),
  HospitalInfoModel(
    nameTC: '長洲醫院',
    nameSC: '长洲医院',
    nameEN: 'St John Hospital',
    contactNo: '2986 2100',
    faxNo: '2981 9050',
    emailAddress: 'sjh_enquiry@ha.org.hk',
  ),
  HospitalInfoModel(
    nameTC: '將軍澳醫院',
    nameSC: '将军澳医院',
    nameEN: 'Tseung Kwan O Hospital',
    contactNo: '2208 0111',
    faxNo: '2177 0161',
    emailAddress: 'tkoh.enquiry@ha.org.hk',
  ),
  HospitalInfoModel(
    nameTC: '屯門醫院',
    nameSC: '屯门医院',
    nameEN: 'Tuen Mun Hospital',
    contactNo: '2468 5111',
    faxNo: '2455 1911',
    emailAddress: 'ntwc.pa@ha.org.hk',
    website: 'http://www.ha.org.hk/tmh',
  ),
  HospitalInfoModel(
    nameTC: '天水圍醫院',
    nameSC: '天水围医院',
    nameEN: 'Tin Shui Wai Hospital',
    contactNo: '3513 5000',
    faxNo: '3514 9129',
    emailAddress: 'tswh.service@ha.org.hk',
    website: 'http://www.ha.org.hk/tswh',
  ),
  HospitalInfoModel(
    nameTC: '基督教聯合醫院',
    nameSC: '基督教联合医院',
    nameEN: 'United Christian Hospital',
    contactNo: '2379 9611',
    faxNo: '2772 7098',
    emailAddress: 'uch.enquiry@ha.org.hk',
    website: 'https://www.ha.org.hk/uch/',
  ),
  HospitalInfoModel(
    nameTC: '仁濟醫院',
    nameSC: '仁济医院',
    nameEN: 'Yan Chai Hospital',
    contactNo: '2417 8383',
    faxNo: '2414 8562',
    emailAddress: 'ych.enquiry@ha.org.hk',
  ),
];
